### ISSUE TITLE
Create tests of the NIFTY container based on  representative sets.

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#11]
Create some integrations tests based on the representative sample of NIFS proposal ID values (see issue #10 for details)

**Comment by Nat1405** [comment]
Just an updated on this: I've reduced 10 of the 35 representative datasets by hand so far as a preliminary test (I'm not sure if we'll be able to make automatic integration tests on cavern before we figure out batch but maybe Brian has some ideas). All 10 of them stopped before completing because of either a bug in Nifty4Gemini or insufficient calibrations being present. @dbohlender @ijiraq do you mind if I spend a bit of my time fixing Nifty4Gemini bugs so these data reductions can succeed without manual intervention?

**Comment by Nat1405** [comment]
(Nifty4Gemini works very well for the programs it was initially built for but I don't think it's ever been tested at this scale).

**Comment by dbohlender** [comment]
Yes, I'd say this should be a pretty high priority.   Yesterday you commented on the poor registration in x/y of two merged cubes.  Is that also something that you are able to look at fixing?

**Comment by Nat1405** [comment]
Thank you.

Yes! I'll definitely look into that too. Hopefully there's an easy headers solution for that one. I'm thinking I'll track the various Nifty4Gemini bug fixes in the [Nifty4Gemini issues tab](https://github.com/Nat1405/Nifty4Gemini/issues) if that sounds good to you.

**Comment by dbohlender** [comment]
👍   (Can you tell I read a bit about GitHub yesterday?  I know how to send emoji's now.)
